# Server settings
server:
  context-path: /common
  port: 8081

spring:
  #profiles : dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#    schema: classpath:import.sql

mybatis:
  typeAliasesPackage: com.unicom.shop.common.domain
# LOGGING
logging:
    path:
#    file: ${catalina.home}/logs/sample.log
    level:
      root: info
      com.unicom.shop.common.mapper: debug
      com.ibatis: info

# custormer message
application:
  message: Hello, Andy